### ISSUE TITLE
Grunt

### ISSUE THREAD

**Issue by jameskoster** [woothemes/storechild#1]
Let's get this baby Grunt powered and remove the CodeKit dependency.

We'll need;
- [x] Compile Sass (include bourbon & susy)
- [x] Compile / minify js
- [x] Watch task for css/js
- [ ] rtlcss (see Storefront Core)

**Comment by mendezcode** [comment]
I'll take care of this one ;-)

**Comment by mendezcode** [comment]
Closed in 6110cfbc84b09c5a1801a5578c8c5b0d91fca810

**Comment by jameskoster** [comment]
@mendezcode Woop! Don't we need to enqueue the rtl css as well? https://github.com/woothemes/storefront/blob/master/inc/class-storefront.php#L169

**Comment by mendezcode** [comment]
@jameskoster, we could but it's not needed, since it's automatically loaded by WordPress when the site is in an RTL language.

If we were using `style-rtl.css`, then it would not be automatically included and we would need to enqueue it manually. This is one of the reasons why the file is renamed from `style-rtl.css` to `rtl.css` on the build task. This way the stylesheet is loaded automatically.

**Comment by mendezcode** [comment]
I realized the `style-rtl.css` file contains not only the overrides, but the entire stylesheet RTL'ed. This means enqueuing the stylesheet and replacing the original styles is the best way to go. Will refactor accordingly ;-)
